    I will cover the pandas from 0 to sql level where u can convert ur sql code to pandas code on leetcode

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shubham kumar\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\shubham kumar\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Ignoring invalid distribution -rotobuf (c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Shubham Kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [9]:
df = pd.DataFrame({
    'Name':['1_Numpy_Code.py', '2_Pandas_Code.py', '3_Matplotlib_Code.py', '4_Seaborn_Code.py', '5_Scikit_Learn_Code.py'],
    "class" : ["NumPy", "Pandas", "Matplotlib", "Seaborn", "Scikit-Learn"]
})

In [10]:
df

                     Name         class
0         1_Numpy_Code.py         NumPy
1        2_Pandas_Code.py        Pandas
2    3_Matplotlib_Code.py    Matplotlib
3       4_Seaborn_Code.py       Seaborn
4  5_Scikit_Learn_Code.py  Scikit-Learn

In [32]:
df = pd.read_csv("iris.csv")

# pd.read_excel("iris.xlsx") # For Excel files
# pd.read_json("iris.json") # For JSON files

In [12]:
df

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

In [13]:
df.head()

   150    4  setosa  versicolor  virginica
0  5.1  3.5     1.4         0.2          0
1  4.9  3.0     1.4         0.2          0
2  4.7  3.2     1.3         0.2          0
3  4.6  3.1     1.5         0.2          0
4  5.0  3.6     1.4         0.2          0

In [15]:
df.shape #row @ column

(150, 5)

In [16]:
df.columns

Index(['150', '4', 'setosa', 'versicolor', 'virginica'], dtype='object')

In [17]:
df.dtypes

150           float64
4             float64
setosa        float64
versicolor    float64
virginica       int64
dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   150         150 non-null    float64
 1   4           150 non-null    float64
 2   setosa      150 non-null    float64
 3   versicolor  150 non-null    float64
 4   virginica   150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [ ]:
df1 = df['150'] # Selecting a column

In [20]:
df1.head() #df1.tail()

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: 150, dtype: float64

In [ ]:
subset = df[['150' , '4']] # Selecting multiple columns

In [23]:
subset.head(10)

   150    4
0  5.1  3.5
1  4.9  3.0
2  4.7  3.2
3  4.6  3.1
4  5.0  3.6
5  5.4  3.9
6  4.6  3.4
7  5.0  3.4
8  4.4  2.9
9  4.9  3.1

In [24]:
print(df['150'])

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: 150, Length: 150, dtype: float64

In [26]:
df.iloc[2:4, 2:5] # Selecting rows and columns by index

   setosa  versicolor  virginica
2     1.3         0.2          0
3     1.5         0.2          0

In [27]:
df.iloc[-1]

150           5.9
4             3.0
setosa        5.1
versicolor    1.8
virginica     2.0
Name: 149, dtype: float64

In [28]:
import numpy as np

arr = np.array([
    [1,2],
    [3,4]
])

df = pd.DataFrame(
    arr,
    columns=["A","B"]
)

print(df)

   A  B
0  1  2
1  3  4

In [ ]:
df.to_csv("mycsv.csv")

In [35]:
df.sample(10)

     150    4  setosa  versicolor  virginica
92   5.8  2.6     4.0         1.2          1
81   5.5  2.4     3.7         1.0          1
63   6.1  2.9     4.7         1.4          1
86   6.7  3.1     4.7         1.5          1
103  6.3  2.9     5.6         1.8          2
131  7.9  3.8     6.4         2.0          2
123  6.3  2.7     4.9         1.8          2
48   5.3  3.7     1.5         0.2          0
125  7.2  3.2     6.0         1.8          2
53   5.5  2.3     4.0         1.3          1

In [36]:
df.describe()

              150           4      setosa  versicolor   virginica
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [38]:
# u know about the series and dataframes 
# arr[] -- series while arr[[]] -- dataframe

In [39]:
df[df["150"]>6]

     150    4  setosa  versicolor  virginica
50   7.0  3.2     4.7         1.4          1
51   6.4  3.2     4.5         1.5          1
52   6.9  3.1     4.9         1.5          1
54   6.5  2.8     4.6         1.5          1
56   6.3  3.3     4.7         1.6          1
..   ...  ...     ...         ...        ...
144  6.7  3.3     5.7         2.5          2
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2

[61 rows x 5 columns]

In [41]:
#multiple conditions
df[
    (df["150"]>5)
    &
    (df["4"]>4)
]

    150    4  setosa  versicolor  virginica
15  5.7  4.4     1.5         0.4          0
32  5.2  4.1     1.5         0.1          0
33  5.5  4.2     1.4         0.2          0

In [42]:
#multiple conditions
df[
    (df["150"]>5)
    |
    (df["4"]>4)
]

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
5    5.4  3.9     1.7         0.4          0
10   5.4  3.7     1.5         0.2          0
14   5.8  4.0     1.2         0.2          0
15   5.7  4.4     1.5         0.4          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[118 rows x 5 columns]

In [43]:
df[
~(df["150"]==6)
]

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[144 rows x 5 columns]

In [44]:
df[
df["150"].isin(
[5,6]
)
]

     150    4  setosa  versicolor  virginica
4    5.0  3.6     1.4         0.2          0
7    5.0  3.4     1.5         0.2          0
25   5.0  3.0     1.6         0.2          0
26   5.0  3.4     1.6         0.4          0
35   5.0  3.2     1.2         0.2          0
40   5.0  3.5     1.3         0.3          0
43   5.0  3.5     1.6         0.6          0
49   5.0  3.3     1.4         0.2          0
60   5.0  2.0     3.5         1.0          1
62   6.0  2.2     4.0         1.0          1
78   6.0  2.9     4.5         1.5          1
83   6.0  2.7     5.1         1.6          1
85   6.0  3.4     4.5         1.6          1
93   5.0  2.3     3.3         1.0          1
119  6.0  2.2     5.0         1.5          2
138  6.0  3.0     4.8         1.8          2

In [45]:
df[
df["150"] > 100
]

Empty DataFrame
Columns: [150, 4, setosa, versicolor, virginica]
Index: []

In [47]:
df[
df["150"]>50000
]

Empty DataFrame
Columns: [150, 4, setosa, versicolor, virginica]
Index: []

In [48]:
df.at[2,"150"]

np.float64(4.7)

In [49]:
df[::-1]

     150    4  setosa  versicolor  virginica
149  5.9  3.0     5.1         1.8          2
148  6.2  3.4     5.4         2.3          2
147  6.5  3.0     5.2         2.0          2
146  6.3  2.5     5.0         1.9          2
145  6.7  3.0     5.2         2.3          2
..   ...  ...     ...         ...        ...
4    5.0  3.6     1.4         0.2          0
3    4.6  3.1     1.5         0.2          0
2    4.7  3.2     1.3         0.2          0
1    4.9  3.0     1.4         0.2          0
0    5.1  3.5     1.4         0.2          0

[150 rows x 5 columns]

In [53]:
#Check Missing Values

df.isnull()
df.isnull().sum()

150           0
4             0
setosa        0
versicolor    0
virginica     0
dtype: int64

In [55]:
df.notnull().sum()

150           150
4             150
setosa        150
versicolor    150
virginica     150
dtype: int64

In [56]:
#Total Missing Values
df.isnull().sum().sum()

np.int64(0)

In [57]:
#drop bhi kar sakte ho missing values ko


df.dropna() # puri ki puri row hi delete ho jayegi / df.dropna(axis=0)

df.dropna(axis = 1) # jo bhi nan value hogi uska column hi delete ho jayega

df.dropna(how = "all") # agar puri row ya column hi nan hai to hi delete hoga

df.dropna(how = "any") # agar kisi bhi row ya column me nan value hai to hi delete ho jayega

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

    Fill Missing Values

In [58]:
df.fillna(0) # -- filling missing values with 0

df.fillna(df.mean())

df.fillna(df.median())

df.fillna(df.min())

df.fillna(df.max())

df.fillna(df.quantile(0.5))

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

    #if you want to fill the mean value of a column

In [60]:
df['150'].fillna(df['150'].mean())

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: 150, Length: 150, dtype: float64

In [ ]:
df["150"].fillna(
    df["150"].median()
)

In [61]:
df.replace("150", "Let")

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

In [63]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [64]:
df.duplicated().sum()

np.int64(1)

In [65]:
df.drop_duplicates(inplace=True)

In [66]:
df.rename(
columns={
"150":"Income"
}
)

     Income    4  setosa  versicolor  virginica
0       5.1  3.5     1.4         0.2          0
1       4.9  3.0     1.4         0.2          0
2       4.7  3.2     1.3         0.2          0
3       4.6  3.1     1.5         0.2          0
4       5.0  3.6     1.4         0.2          0
..      ...  ...     ...         ...        ...
145     6.7  3.0     5.2         2.3          2
146     6.3  2.5     5.0         1.9          2
147     6.5  3.0     5.2         2.0          2
148     6.2  3.4     5.4         2.3          2
149     5.9  3.0     5.1         1.8          2

[149 rows x 5 columns]

In [ ]:
df["Name"] = df["Name"].str.strip()  #for future project

df["Department"].str.upper()

df["Department"].str.lower()

df["Department"].str.capitalize()

    Find Missing Percentage

In [67]:
(df.isnull().sum()/len(df))*100

150           0.0
4             0.0
setosa        0.0
versicolor    0.0
virginica     0.0
dtype: float64

In [68]:
df.nunique()

150           35
4             23
setosa        43
versicolor    22
virginica      3
dtype: int64

In [70]:
df["150"].unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [72]:
df["150"].value_counts()

150
5.0    10
5.1     9
6.3     9
6.7     8
5.7     8
5.5     7
6.4     7
4.9     6
5.8     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: count, dtype: int64

    Data Manipulation

In [73]:
import pandas as pd

data = {
    "Name":["Rahul","Aman","Neha","Priya","Rohit"],
    "Age":[22,25,21,24,26],
    "Salary":[50000,70000,45000,65000,80000],
    "Department":["IT","HR","IT","Finance","HR"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary Department
0  Rahul   22   50000         IT
1   Aman   25   70000         HR
2   Neha   21   45000         IT
3  Priya   24   65000    Finance
4  Rohit   26   80000         HR

In [75]:
df.sort_values("Salary")

    Name  Age  Salary Department
2   Neha   21   45000         IT
0  Rahul   22   50000         IT
3  Priya   24   65000    Finance
1   Aman   25   70000         HR
4  Rohit   26   80000         HR

In [76]:
df.sort_values(
    "Salary",
    ascending=False
)

    Name  Age  Salary Department
4  Rohit   26   80000         HR
1   Aman   25   70000         HR
3  Priya   24   65000    Finance
0  Rahul   22   50000         IT
2   Neha   21   45000         IT

In [77]:
df.sort_index()

    Name  Age  Salary Department
0  Rahul   22   50000         IT
1   Aman   25   70000         HR
2   Neha   21   45000         IT
3  Priya   24   65000    Finance
4  Rohit   26   80000         HR

In [79]:
df.sort_values("Salary")

    Name  Age  Salary Department
2   Neha   21   45000         IT
0  Rahul   22   50000         IT
3  Priya   24   65000    Finance
1   Aman   25   70000         HR
4  Rohit   26   80000         HR

In [80]:
df.sort_values(
    "Salary",
    ascending=False
)

    Name  Age  Salary Department
4  Rohit   26   80000         HR
1   Aman   25   70000         HR
3  Priya   24   65000    Finance
0  Rahul   22   50000         IT
2   Neha   21   45000         IT

In [81]:
df.insert(
1,
"Gender",
["M","M","F","F","M"]
)

In [82]:
df

    Name Gender  Age  Salary Department
0  Rahul      M   22   50000         IT
1   Aman      M   25   70000         HR
2   Neha      F   21   45000         IT
3  Priya      F   24   65000    Finance
4  Rohit      M   26   80000         HR

In [83]:
df = df.assign(
Bonus=df["Salary"]*0.10
)

In [85]:
df["Bonus"] = df["Salary"]*0.10

In [86]:
df

    Name Gender  Age  Salary Department   Bonus
0  Rahul      M   22   50000         IT  5000.0
1   Aman      M   25   70000         HR  7000.0
2   Neha      F   21   45000         IT  4500.0
3  Priya      F   24   65000    Finance  6500.0
4  Rohit      M   26   80000         HR  8000.0

In [87]:
df.drop(
"Bonus",
axis=1
)

    Name Gender  Age  Salary Department
0  Rahul      M   22   50000         IT
1   Aman      M   25   70000         HR
2   Neha      F   21   45000         IT
3  Priya      F   24   65000    Finance
4  Rohit      M   26   80000         HR

In [88]:
df.drop(2)

    Name Gender  Age  Salary Department   Bonus
0  Rahul      M   22   50000         IT  5000.0
1   Aman      M   25   70000         HR  7000.0
3  Priya      F   24   65000    Finance  6500.0
4  Rohit      M   26   80000         HR  8000.0

In [89]:
bonus = df.pop("Bonus")

In [90]:
df['Salary'] = df['Salary'].apply(lambda x : x*100)

In [91]:
df

    Name Gender  Age   Salary Department
0  Rahul      M   22  5000000         IT
1   Aman      M   25  7000000         HR
2   Neha      F   21  4500000         IT
3  Priya      F   24  6500000    Finance
4  Rohit      M   26  8000000         HR

In [93]:
#Mapping is also there 

gender = {
"M":"Male",
"F":"Female"
}

df["Gender"] = df["Gender"].map(gender)

In [94]:
df #here m is going to become the Male and f is going to become the Female

    Name  Gender  Age   Salary Department
0  Rahul    Male   22  5000000         IT
1   Aman    Male   25  7000000         HR
2   Neha  Female   21  4500000         IT
3  Priya  Female   24  6500000    Finance
4  Rohit    Male   26  8000000         HR

In [95]:
df.replace({
"IT":"Technology",
"HR":"Human Resource"
})

    Name  Gender  Age   Salary      Department
0  Rahul    Male   22  5000000      Technology
1   Aman    Male   25  7000000  Human Resource
2   Neha  Female   21  4500000      Technology
3  Priya  Female   24  6500000         Finance
4  Rohit    Male   26  8000000  Human Resource

In [96]:
new_df = df.copy()

In [97]:
new_df

    Name  Gender  Age   Salary Department
0  Rahul    Male   22  5000000         IT
1   Aman    Male   25  7000000         HR
2   Neha  Female   21  4500000         IT
3  Priya  Female   24  6500000    Finance
4  Rohit    Male   26  8000000         HR

In [98]:
df.set_index("Name")

       Gender  Age   Salary Department
Name
Rahul    Male   22  5000000         IT
Aman     Male   25  7000000         HR
Neha   Female   21  4500000         IT
Priya  Female   24  6500000    Finance
Rohit    Male   26  8000000         HR

In [99]:
df.rename(
columns={
"Salary":"Income"
}
)

    Name  Gender  Age   Income Department
0  Rahul    Male   22  5000000         IT
1   Aman    Male   25  7000000         HR
2   Neha  Female   21  4500000         IT
3  Priya  Female   24  6500000    Finance
4  Rohit    Male   26  8000000         HR

In [100]:
df['Salary'].round(2)

0    5000000
1    7000000
2    4500000
3    6500000
4    8000000
Name: Salary, dtype: int64

In [101]:
df["Age"].map(lambda x: x + 1)

0    23
1    26
2    22
3    25
4    27
Name: Age, dtype: int64

In [102]:
df["Age"].apply(lambda x: x + 1)

0    23
1    26
2    22
3    25
4    27
Name: Age, dtype: int64

In [103]:
df.applymap(lambda x: x)

C:\Users\Shubham Kumar\AppData\Local\Temp\ipykernel_25224\3484062150.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x)

    Name  Gender  Age   Salary Department
0  Rahul    Male   22  5000000         IT
1   Aman    Male   25  7000000         HR
2   Neha  Female   21  4500000         IT
3  Priya  Female   24  6500000    Finance
4  Rohit    Male   26  8000000         HR

    Q1. Difference between apply() and map()?
    map() works only on a Series.
    apply() can work on a Series and also on a DataFrame (across rows or columns using the axis parameter).
    Q2. Difference between drop() and pop()?
    drop() removes rows or columns.
    pop() removes a column and returns it.
    Q3. Why use clip()?
    To limit values within a specified range, often for handling outliers.
    Q4. Difference between insert() and assign()?
    insert() adds a column at a specific position.
    assign() creates a new column (typically at the end) and returns a new DataFrame.
    Q5. Why use copy()?
    To create an independent copy so changes don't affect the original DataFrame.

In [104]:
import pandas as pd

data = {
    "Name": ["Rahul", "Aman", "Neha", "Priya", "Rohit", "Karan", "Sneha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Gender": ["M", "M", "F", "F", "M", "M", "F"],
    "Age": [22, 25, 21, 24, 26, 28, 23],
    "Salary": [50000, 70000, 45000, 65000, 80000, 90000, 60000]
}

df = pd.DataFrame(data)

print(df)

    Name Department Gender  Age  Salary
0  Rahul         IT      M   22   50000
1   Aman         HR      M   25   70000
2   Neha         IT      F   21   45000
3  Priya    Finance      F   24   65000
4  Rohit         HR      M   26   80000
5  Karan         IT      M   28   90000
6  Sneha    Finance      F   23   60000

In [108]:
df.groupby("Department")

In [110]:
df.groupby("Department")['Salary'].mean()

Department
Finance    62500.000000
HR         75000.000000
IT         61666.666667
Name: Salary, dtype: float64

In [111]:
df.groupby("Department")['Salary'].sum()

Department
Finance    125000
HR         150000
IT         185000
Name: Salary, dtype: int64

In [112]:
df.groupby("Department")['Salary'].max()

Department
Finance    65000
HR         80000
IT         90000
Name: Salary, dtype: int64

In [113]:
df.groupby("Department")["Salary"].median()

Department
Finance    62500.0
HR         75000.0
IT         50000.0
Name: Salary, dtype: float64

In [114]:

df.groupby("Department")["Salary"].std()

Department
Finance     3535.533906
HR          7071.067812
IT         24664.414312
Name: Salary, dtype: float64

In [115]:
#here is the aggregation function which is used to perform multiple operations on the grouped data. It allows you to specify a list of aggregation functions to apply to each group, and it returns a new DataFrame with the results of those aggregations.
df.groupby("Department")["Salary"].agg(
    ["mean", "max", "min", "sum", "count"]
)

                    mean    max    min     sum  count
Department
Finance     62500.000000  65000  60000  125000      2
HR          75000.000000  80000  70000  150000      2
IT          61666.666667  90000  45000  185000      3

In [116]:
df.groupby("Department").agg({
    "Salary": ["mean", "max"],
    "Age": ["min", "max"]
})

                  Salary        Age
                    mean    max min max
Department
Finance     62500.000000  65000  23  24
HR          75000.000000  80000  25  26
IT          61666.666667  90000  21  28

In [117]:
df.groupby("Department").size()

Department
Finance    2
HR         2
IT         3
dtype: int64

In [118]:
df["Department"].value_counts()

Department
IT         3
HR         2
Finance    2
Name: count, dtype: int64

In [123]:
print(df["Department"].unique())
print(df["Department"].nunique())

['IT' 'HR' 'Finance']
3

In [124]:
df.groupby(
"Department"
)["Salary"].mean().sort_values()

Department
IT         61666.666667
Finance    62500.000000
HR         75000.000000
Name: Salary, dtype: float64

In [125]:
df.groupby(
"Department"
)["Salary"].rank()

0    2.0
1    1.0
2    1.0
3    2.0
4    2.0
5    3.0
6    1.0
Name: Salary, dtype: float64

In [126]:
df["Dept Avg Salary"] = df.groupby(
"Department"
)["Salary"].transform("mean")

In [127]:
df

    Name Department Gender  Age  Salary  Dept Avg Salary
0  Rahul         IT      M   22   50000     61666.666667
1   Aman         HR      M   25   70000     75000.000000
2   Neha         IT      F   21   45000     61666.666667
3  Priya    Finance      F   24   65000     62500.000000
4  Rohit         HR      M   26   80000     75000.000000
5  Karan         IT      M   28   90000     61666.666667
6  Sneha    Finance      F   23   60000     62500.000000

In [128]:
df.groupby(
"Department"
).filter(
lambda x: len(x) > 2
)

    Name Department Gender  Age  Salary  Dept Avg Salary
0  Rahul         IT      M   22   50000     61666.666667
2   Neha         IT      F   21   45000     61666.666667
5  Karan         IT      M   28   90000     61666.666667

In [130]:
df.groupby(
"Department"
).first()

#it will return the first row of each department

# df.groupby(
# "Department"
# ).last()

             Name Gender  Age  Salary  Dept Avg Salary
Department
Finance     Sneha      F   23   60000     62500.000000
HR          Rohit      M   26   80000     75000.000000
IT          Karan      M   28   90000     61666.666667

In [131]:
dept_salary = df.groupby(
"Department"
)["Salary"].mean()

In [132]:
df

    Name Department Gender  Age  Salary  Dept Avg Salary
0  Rahul         IT      M   22   50000     61666.666667
1   Aman         HR      M   25   70000     75000.000000
2   Neha         IT      F   21   45000     61666.666667
3  Priya    Finance      F   24   65000     62500.000000
4  Rohit         HR      M   26   80000     75000.000000
5  Karan         IT      M   28   90000     61666.666667
6  Sneha    Finance      F   23   60000     62500.000000

    Merging & Combining DataFrames

In [133]:
employee = pd.DataFrame({
    "Emp_ID":[101,102,103,104],
    "Name":["Rahul","Aman","Neha","Priya"],
    "Department":["IT","HR","Finance","IT"]
})

print(employee)

   Emp_ID   Name Department
0     101  Rahul         IT
1     102   Aman         HR
2     103   Neha    Finance
3     104  Priya         IT

In [134]:
salary = pd.DataFrame({
    "Emp_ID":[101,102,103,105],
    "Salary":[50000,70000,60000,80000]
})

print(salary)

   Emp_ID  Salary
0     101   50000
1     102   70000
2     103   60000
3     105   80000

In [135]:
pd.concat([employee, salary]) #vertical concatenation

   Emp_ID   Name Department   Salary
0     101  Rahul         IT      NaN
1     102   Aman         HR      NaN
2     103   Neha    Finance      NaN
3     104  Priya         IT      NaN
0     101    NaN        NaN  50000.0
1     102    NaN        NaN  70000.0
2     103    NaN        NaN  60000.0
3     105    NaN        NaN  80000.0

In [136]:
pd.concat([employee, salary], axis=1) #horizontal concatenation

   Emp_ID   Name Department  Emp_ID  Salary
0     101  Rahul         IT     101   50000
1     102   Aman         HR     102   70000
2     103   Neha    Finance     103   60000
3     104  Priya         IT     105   80000

In [137]:
pd.merge(employee, salary , on = "Emp_ID") # default case mein yeh inner join hi hota hai

   Emp_ID   Name Department  Salary
0     101  Rahul         IT   50000
1     102   Aman         HR   70000
2     103   Neha    Finance   60000

In [138]:
pd.merge(employee, salary , on = "Emp_ID" , how = "left") # left join

   Emp_ID   Name Department   Salary
0     101  Rahul         IT  50000.0
1     102   Aman         HR  70000.0
2     103   Neha    Finance  60000.0
3     104  Priya         IT      NaN

In [139]:
pd.merge(employee, salary , on = "Emp_ID" , how = "right") # right join

   Emp_ID   Name Department  Salary
0     101  Rahul         IT   50000
1     102   Aman         HR   70000
2     103   Neha    Finance   60000
3     105    NaN        NaN   80000

In [140]:
pd.merge(employee, salary , on = "Emp_ID" , how = "outer") # outer join

   Emp_ID   Name Department   Salary
0     101  Rahul         IT  50000.0
1     102   Aman         HR  70000.0
2     103   Neha    Finance  60000.0
3     104  Priya         IT      NaN
4     105    NaN        NaN  80000.0

    🎯 AI/ML Interview Questions
    Q1. Difference between merge() and concat()?
    merge()	concat()
    SQL Join	Stack DataFrames
    Needs common key	Doesn't need a key
    Q2. Difference between Left Join and Inner Join?

    Inner Join

    Keeps only matching rows.

    Left Join

    Keeps all rows from the left DataFrame, filling unmatched values with NaN.

    Q3. Difference between join() and merge()?
    merge() joins using one or more columns.
    join() joins primarily using the index.
    Q4. What is indicator=True used for?

    It adds a column showing whether each row came from:

    left_only
    right_only
    both

    This is very useful for debugging joins.

    Q5. Why is concat() preferred over append()?

    Because append() has been deprecated in modern versions of Pandas. pd.concat() is the recommended replacement.

In [144]:
import pandas as pd

data = {
    "Name": [" Rahul ", "AMAN", "neha", "Priya", "rohit"],
    "Email": [
        "rahul@gmail.com",
        "aman@yahoo.com",
        "neha@gmail.com",
        "priya@hotmail.com",
        "rohit@gmail.com"
    ],
    "Department": ["IT", "HR", "Finance", "IT", "HR"],
    "Joining_Date": [
        "2022-01-10",
        "2021-06-15",
        "2023-03-20",
        "2020-12-01",
        "2022-08-25"
    ]
}

df = pd.DataFrame(data)

print(df)

      Name              Email Department Joining_Date
0   Rahul     rahul@gmail.com         IT   2022-01-10
1     AMAN     aman@yahoo.com         HR   2021-06-15
2     neha     neha@gmail.com    Finance   2023-03-20
3    Priya  priya@hotmail.com         IT   2020-12-01
4    rohit    rohit@gmail.com         HR   2022-08-25

    STRING OPERATIONS

In [145]:
df["Name"].str.upper()

df["Name"].str.lower()

df["Name"].str.title()

df["Name"].str.capitalize()

df["Name"].str.contains("Shubham")

df["Name"].str.startswith("Shubham")

df["Name"].str.endswith("Kumar")

df["Name"].str.len()

df["Name"].str.find("Shubham")

df["Name"].str.slice(0, 5)

df["Name"].str.split()

df["Name"].str.rsplit()

df["Name"].str.extract("(\w+) (\w+)")

df["Name"].str.replace("Shubham", "Shubham Kumar")

df["Name"].str.pad(10, side="left", fillchar="0")

0    000 Rahul
1    000000AMAN
2    000000neha
3    00000Priya
4    00000rohit
Name: Name, dtype: object

In [146]:
df["Full"] = (
df["Name"] +
" - " +
df["Department"]
)

In [147]:
df

      Name              Email Department Joining_Date            Full
0   Rahul     rahul@gmail.com         IT   2022-01-10     Rahul  - IT
1     AMAN     aman@yahoo.com         HR   2021-06-15       AMAN - HR
2     neha     neha@gmail.com    Finance   2023-03-20  neha - Finance
3    Priya  priya@hotmail.com         IT   2020-12-01      Priya - IT
4    rohit    rohit@gmail.com         HR   2022-08-25      rohit - HR

In [148]:
df[
df["Name"].str.len()>5
]

      Name            Email Department Joining_Date          Full
0   Rahul   rahul@gmail.com         IT   2022-01-10   Rahul  - IT

In [149]:
df["Joining_Date"] = pd.to_datetime(
df["Joining_Date"]
)

In [150]:
df

      Name              Email Department Joining_Date            Full
0   Rahul     rahul@gmail.com         IT   2022-01-10     Rahul  - IT
1     AMAN     aman@yahoo.com         HR   2021-06-15       AMAN - HR
2     neha     neha@gmail.com    Finance   2023-03-20  neha - Finance
3    Priya  priya@hotmail.com         IT   2020-12-01      Priya - IT
4    rohit    rohit@gmail.com         HR   2022-08-25      rohit - HR

In [151]:
df["Joining_Date"].dt.year

0    2022
1    2021
2    2023
3    2020
4    2022
Name: Joining_Date, dtype: int32

In [152]:
df["Joining_Date"].dt.month

0     1
1     6
2     3
3    12
4     8
Name: Joining_Date, dtype: int32

In [153]:
df["Joining_Date"].dt.day

0    10
1    15
2    20
3     1
4    25
Name: Joining_Date, dtype: int32

In [154]:
df["Joining_Date"].dt.day_name()

0      Monday
1     Tuesday
2      Monday
3     Tuesday
4    Thursday
Name: Joining_Date, dtype: object

In [155]:
pd.Timestamp.today()

Timestamp('2026-07-25 11:35:12.576032')

In [156]:
today = pd.Timestamp.today()

df["Experience"] = (
today -
df["Joining_Date"]
)

In [157]:
df

,Name,Email,Department,Joining_Date,Full,Experience
0,Rahul,rahul@gmail.com,IT,2022-01-10,Rahul - IT,1657 days 11:35:49.063933
1,AMAN,aman@yahoo.com,HR,2021-06-15,AMAN - HR,1866 days 11:35:49.063933
2,neha,neha@gmail.com,Finance,2023-03-20,neha - Finance,1223 days 11:35:49.063933
3,Priya,priya@hotmail.com,IT,2020-12-01,Priya - IT,2062 days 11:35:49.063933
4,rohit,rohit@gmail.com,HR,2022-08-25,rohit - HR,1430 days 11:35:49.063933

In [158]:
df["Experience"].dt.days

0    1657
1    1866
2    1223
3    2062
4    1430
Name: Experience, dtype: int64

In [159]:
df.sort_values(
"Joining_Date"
)

,Name,Email,Department,Joining_Date,Full,Experience
3,Priya,priya@hotmail.com,IT,2020-12-01,Priya - IT,2062 days 11:35:49.063933
1,AMAN,aman@yahoo.com,HR,2021-06-15,AMAN - HR,1866 days 11:35:49.063933
0,Rahul,rahul@gmail.com,IT,2022-01-10,Rahul - IT,1657 days 11:35:49.063933
4,rohit,rohit@gmail.com,HR,2022-08-25,rohit - HR,1430 days 11:35:49.063933
2,neha,neha@gmail.com,Finance,2023-03-20,neha - Finance,1223 days 11:35:49.063933

In [160]:
df["Joining_Date"] + pd.Timedelta(days=10)

0   2022-01-20
1   2021-06-25
2   2023-03-30
3   2020-12-11
4   2022-09-04
Name: Joining_Date, dtype: datetime64[ns]

In [161]:
df["Joining_Date"] + pd.Timedelta(days=10)

0   2022-01-20
1   2021-06-25
2   2023-03-30
3   2020-12-11
4   2022-09-04
Name: Joining_Date, dtype: datetime64[ns]

In [162]:
df["Joining_Date"].dt.dayofweek >= 5

0    False
1    False
2    False
3    False
4    False
Name: Joining_Date, dtype: bool

    🎯 AI/ML Interview Questions
    Q1. Why use .str methods instead of Python string methods?

    Because .str methods work vectorized on an entire Pandas Series, making them much faster and cleaner.

    Q2. Difference between strip(), lstrip(), and rstrip()?
    Function	Removes
    strip()	Both left & right spaces
    lstrip()	Left spaces only
    rstrip()	Right spaces only
    Q3. Why use pd.to_datetime()?

    To convert string dates into datetime objects so you can easily extract year, month, day, perform filtering, sorting, and date arithmetic.

    Q4. What is the .dt accessor?

    .dt provides vectorized access to datetime properties such as:

    year
    month
    day
    day_name()
    quarter
    days
    Q5. Why extract year or month in ML?

    Models cannot directly understand datetime objects. We convert them into numerical features like:

    Joining Year
    Month
    Day
    Quarter
    Experience (in years)

    These become useful input features for machine learning algorithms.

In [163]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age":[22,25,21,24,26],
    "Salary":[50000,70000,45000,65000,80000],
    "Experience":[1,3,1,2,4],
    "Department":["IT","HR","IT","Finance","HR"]
})

print(df)

   Age  Salary  Experience Department
0   22   50000           1         IT
1   25   70000           3         HR
2   21   45000           1         IT
3   24   65000           2    Finance
4   26   80000           4         HR

    Advanced Pandas

In [164]:
df.corr(numeric_only=True)

                 Age    Salary  Experience
Age         1.000000  0.995964    0.961645
Salary      0.995964  1.000000    0.971694
Experience  0.961645  0.971694    1.000000

In [165]:
df.cov(numeric_only=True)

                Age       Salary  Experience
Age             4.3      29750.0         2.6
Salary      29750.0  207500000.0     18250.0
Experience      2.6      18250.0         1.7

In [166]:
df.memory_usage()

Index         132
Age            40
Salary         40
Experience     40
Department     40
dtype: int64

In [168]:
# df.nlargest(
# 3,
# "Salary"
# )


df.nsmallest(
3,
"Salary"
)

   Age  Salary  Experience Department
2   21   45000           1         IT
0   22   50000           1         IT
3   24   65000           2    Finance

In [169]:
df["Salary"].idxmin()  # Get the index of the minimum salary
df["Salary"].idxmax()  # Get the index of the maximum salary
df["Salary"].idxmin(axis=1)  # Get the row index of the minimum salary
df["Salary"].idxmax(axis=1)  # Get the row index of the maximum salary

2

In [170]:
df.stack

<bound method DataFrame.stack of    Age  Salary  Experience Department
0   22   50000           1         IT
1   25   70000           3         HR
2   21   45000           1         IT
3   24   65000           2    Finance
4   26   80000           4         HR>

In [171]:
df.query(
"Salary>50000"
)

   Age  Salary  Experience Department
1   25   70000           3         HR
3   24   65000           2    Finance
4   26   80000           4         HR

    Read Large CSV Efficiently

    pd.read_csv(
    "data.csv",
    chunksize=10000
    )

    Complete AI/ML Workflow

    CSV
    │
    ▼
    read_csv()
    │
    ▼
    head()

    info()

    describe()
    │
    ▼
    isnull()

    fillna()

    drop_duplicates()
    │
    ▼
    astype()

    rename()

    replace()
    │
    ▼
    groupby()

    pivot_table()

    value_counts()
    │
    ▼
    Feature Engineering
    │
    ▼
    Encoding
    │
    ▼
    Train-Test Split
    │
    ▼
    Machine Learning Model
    │
    ▼
    Evaluation

    Pandas Interview Cheat Sheet
    
    Function	Purpose
    read_csv()	Read CSV
    head()	First rows
    tail()	Last rows
    info()	Dataset info
    describe()	Statistics
    shape	Rows × Columns
    columns	Column names
    dtypes	Datatypes
    isnull()	Missing values
    fillna()	Fill missing values
    dropna()	Remove missing values
    duplicated()	Duplicate rows
    drop_duplicates()	Remove duplicates
    astype()	Change datatype
    loc	Label indexing
    iloc	Position indexing
    at	Single label value
    iat	Single positional value
    sort_values()	Sort rows
    value_counts()	Frequency
    unique()	Unique values
    nunique()	Count unique
    groupby()	Group data
    agg()	Aggregation
    transform()	Feature engineering
    pivot_table()	Summary table
    crosstab()	Category comparison
    merge()	SQL join
    concat()	Combine DataFrames
    join()	Index join
    map()	Mapping
    apply()	Apply function
    query()	SQL-like filtering
    corr()	Correlation
    cut()	Equal-width bins
    qcut()	Equal-frequency bins
    explode()	Expand list values
    memory_usage()	Memory analysis

# AI/ML Data Preprocessing – Interview Questions & Answers

## 1. How to Detect Missing Values?

Missing values are common in real-world datasets and must be identified before training a machine learning model.

### Check Missing Values

```python
import pandas as pd

# Count missing values in each column
df.isnull().sum()

# Percentage of missing values
(df.isnull().sum() / len(df)) * 100

# Check if dataset contains any missing values
df.isnull().values.any()
```

### Best Practices

* Remove columns with excessive missing values.
* Fill numerical columns using Mean or Median.
* Fill categorical columns using Mode.
* Use advanced techniques like KNN Imputer or Iterative Imputer when required.

---

# 2. How to Remove Duplicates?

Duplicate records can bias model training and affect performance.

### Find Duplicate Rows

```python
df.duplicated().sum()
```

### Remove Duplicate Rows

```python
df = df.drop_duplicates()
```

### Remove Duplicates Based on Specific Columns

```python
df = df.drop_duplicates(subset=["Customer_ID"])
```

---

# 3. How to Encode Categorical Data?

Machine Learning models require numerical input, so categorical variables must be converted into numbers.

### Label Encoding

Suitable for ordinal categories.

```python
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])
```

---

### One-Hot Encoding

Suitable for nominal categories.

```python
df = pd.get_dummies(df,
                    columns=["City"],
                    drop_first=True)
```

---

### Ordinal Encoding

```python
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

df[["Education"]] = encoder.fit_transform(df[["Education"]])
```

---

# 4. How to Identify Outliers?

Outliers are extreme values that differ significantly from other observations.

## Using Box Plot

```python
import seaborn as sns

sns.boxplot(x=df["Salary"])
```

---

## Using IQR Method

```python
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["Salary"] < lower) |
              (df["Salary"] > upper)]
```

---

## Using Z-Score

```python
from scipy.stats import zscore

df["zscore"] = zscore(df["Salary"])

outliers = df[df["zscore"].abs() > 3]
```

---

# 5. How to Perform Feature Engineering?

Feature Engineering improves model performance by creating informative features.

### Create New Features

```python
df["TotalIncome"] = df["Salary"] + df["Bonus"]
```

---

### Date Feature Extraction

```python
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

df["Year"] = df["Joining_Date"].dt.year
df["Month"] = df["Joining_Date"].dt.month
df["Day"] = df["Joining_Date"].dt.day
```

---

### Binning

```python
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,18,35,60,100],
    labels=["Child","Young","Adult","Senior"]
)
```

---

### Feature Scaling

```python
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["Salary"]] = scaler.fit_transform(df[["Salary"]])
```

---

# 6. How to Merge Multiple Datasets?

Pandas provides different ways to combine datasets.

### Merge

```python
merged = pd.merge(df1,
                  df2,
                  on="Customer_ID",
                  how="inner")
```

---

### Left Join

```python
pd.merge(df1, df2,
         on="Customer_ID",
         how="left")
```

---

### Right Join

```python
pd.merge(df1, df2,
         on="Customer_ID",
         how="right")
```

---

### Outer Join

```python
pd.merge(df1, df2,
         on="Customer_ID",
         how="outer")
```

---

### Concatenate

```python
pd.concat([df1, df2],
          axis=0)
```

---

# 7. How to Optimize Pandas Performance?

Large datasets require efficient operations.

### Specify Data Types

```python
df = pd.read_csv(
    "data.csv",
    dtype={"Age":"int32",
           "Salary":"float32"}
)
```

---

### Use Categorical Data Type

```python
df["City"] = df["City"].astype("category")
```

---

### Vectorized Operations

Instead of

```python
for i in range(len(df)):
    df.loc[i, "Salary"] *= 1.1
```

Use

```python
df["Salary"] *= 1.1
```

---

### Read Only Required Columns

```python
df = pd.read_csv(
    "data.csv",
    usecols=["Age","Salary"]
)
```

---

# 8. How to Handle Class Imbalance?

Imbalanced datasets can lead to biased predictions.

### Check Distribution

```python
df["Target"].value_counts()
```

---

### Random Oversampling

```python
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler()

X_resampled, y_resampled = ros.fit_resample(X, y)
```

---

### SMOTE

```python
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)
```

---

### Class Weights

```python
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    class_weight="balanced"
)
```

---

# 9. How to Prepare Data Before Model Training?

Typical preprocessing steps include:

* Load dataset
* Remove duplicates
* Handle missing values
* Encode categorical variables
* Detect and treat outliers
* Scale numerical features
* Feature engineering
* Split dataset
* Train model

### Train-Test Split

```python
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
```

---

# 10. Explain the Complete Preprocessing Pipeline

A production-ready preprocessing pipeline ensures consistent transformations during both training and inference.

```python
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

numeric_features = ["Age", "Salary"]

categorical_features = ["City", "Gender"]

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)
```

---

# Complete AI/ML Data Preprocessing Workflow

```
Raw Dataset
      │
      ▼
Load Data
      │
      ▼
Understand Dataset
      │
      ▼
Handle Missing Values
      │
      ▼
Remove Duplicate Records
      │
      ▼
Detect & Treat Outliers
      │
      ▼
Encode Categorical Features
      │
      ▼
Feature Engineering
      │
      ▼
Feature Scaling
      │
      ▼
Handle Class Imbalance
      │
      ▼
Train-Test Split
      │
      ▼
Preprocessing Pipeline
      │
      ▼
Model Training
      │
      ▼
Model Evaluation
      │
      ▼
Model Deployment
```

## Interview Tips

* Always perform preprocessing **after understanding the dataset**.
* Fit preprocessing objects (scalers, imputers, encoders) **only on the training data** and apply them to validation/test data using `.transform()`.
* Use **Pipelines** and **ColumnTransformer** to avoid data leakage and keep preprocessing reproducible.
* Handle missing values before encoding or scaling.
* Check for class imbalance before selecting evaluation metrics and training the model.