    I will cover the pandas from 0 to sql level where u can convert ur sql code to pandas code on leetcode

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shubham kumar\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\shubham kumar\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Ignoring invalid distribution -rotobuf (c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\shubham kumar\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Shubham Kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [9]:
df = pd.DataFrame({
    'Name':['1_Numpy_Code.py', '2_Pandas_Code.py', '3_Matplotlib_Code.py', '4_Seaborn_Code.py', '5_Scikit_Learn_Code.py'],
    "class" : ["NumPy", "Pandas", "Matplotlib", "Seaborn", "Scikit-Learn"]
})

In [10]:
df

                     Name         class
0         1_Numpy_Code.py         NumPy
1        2_Pandas_Code.py        Pandas
2    3_Matplotlib_Code.py    Matplotlib
3       4_Seaborn_Code.py       Seaborn
4  5_Scikit_Learn_Code.py  Scikit-Learn

In [32]:
df = pd.read_csv("iris.csv")

# pd.read_excel("iris.xlsx") # For Excel files
# pd.read_json("iris.json") # For JSON files

In [12]:
df

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

In [13]:
df.head()

   150    4  setosa  versicolor  virginica
0  5.1  3.5     1.4         0.2          0
1  4.9  3.0     1.4         0.2          0
2  4.7  3.2     1.3         0.2          0
3  4.6  3.1     1.5         0.2          0
4  5.0  3.6     1.4         0.2          0

In [ ]:
df.shape #row @ column

(150, 5)

In [16]:
df.columns

Index(['150', '4', 'setosa', 'versicolor', 'virginica'], dtype='object')

In [17]:
df.dtypes

150           float64
4             float64
setosa        float64
versicolor    float64
virginica       int64
dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   150         150 non-null    float64
 1   4           150 non-null    float64
 2   setosa      150 non-null    float64
 3   versicolor  150 non-null    float64
 4   virginica   150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [ ]:
df1 = df['150'] # Selecting a column

In [ ]:
df1.head() #df1.tail()

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: 150, dtype: float64

In [ ]:
subset = df[['150' , '4']] # Selecting multiple columns

In [23]:
subset.head(10)

   150    4
0  5.1  3.5
1  4.9  3.0
2  4.7  3.2
3  4.6  3.1
4  5.0  3.6
5  5.4  3.9
6  4.6  3.4
7  5.0  3.4
8  4.4  2.9
9  4.9  3.1

In [24]:
print(df['150'])

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: 150, Length: 150, dtype: float64

In [ ]:
df.iloc[2:4, 2:5] # Selecting rows and columns by index

   setosa  versicolor  virginica
2     1.3         0.2          0
3     1.5         0.2          0

In [27]:
df.iloc[-1]

150           5.9
4             3.0
setosa        5.1
versicolor    1.8
virginica     2.0
Name: 149, dtype: float64

In [28]:
import numpy as np

arr = np.array([
    [1,2],
    [3,4]
])

df = pd.DataFrame(
    arr,
    columns=["A","B"]
)

print(df)

   A  B
0  1  2
1  3  4

In [ ]:
df.to_csv("mycsv.csv")

In [35]:
df.sample(10)

     150    4  setosa  versicolor  virginica
92   5.8  2.6     4.0         1.2          1
81   5.5  2.4     3.7         1.0          1
63   6.1  2.9     4.7         1.4          1
86   6.7  3.1     4.7         1.5          1
103  6.3  2.9     5.6         1.8          2
131  7.9  3.8     6.4         2.0          2
123  6.3  2.7     4.9         1.8          2
48   5.3  3.7     1.5         0.2          0
125  7.2  3.2     6.0         1.8          2
53   5.5  2.3     4.0         1.3          1

In [36]:
df.describe()

              150           4      setosa  versicolor   virginica
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [38]:
# u know about the series and dataframes 
# arr[] -- series while arr[[]] -- dataframe

In [39]:
df[df["150"]>6]

     150    4  setosa  versicolor  virginica
50   7.0  3.2     4.7         1.4          1
51   6.4  3.2     4.5         1.5          1
52   6.9  3.1     4.9         1.5          1
54   6.5  2.8     4.6         1.5          1
56   6.3  3.3     4.7         1.6          1
..   ...  ...     ...         ...        ...
144  6.7  3.3     5.7         2.5          2
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2

[61 rows x 5 columns]

In [ ]:
#multiple conditions
df[
    (df["150"]>5)
    &
    (df["4"]>4)
]

    150    4  setosa  versicolor  virginica
15  5.7  4.4     1.5         0.4          0
32  5.2  4.1     1.5         0.1          0
33  5.5  4.2     1.4         0.2          0

In [42]:
#multiple conditions
df[
    (df["150"]>5)
    |
    (df["4"]>4)
]

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
5    5.4  3.9     1.7         0.4          0
10   5.4  3.7     1.5         0.2          0
14   5.8  4.0     1.2         0.2          0
15   5.7  4.4     1.5         0.4          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[118 rows x 5 columns]

In [43]:
df[
~(df["150"]==6)
]

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[144 rows x 5 columns]

In [44]:
df[
df["150"].isin(
[5,6]
)
]

     150    4  setosa  versicolor  virginica
4    5.0  3.6     1.4         0.2          0
7    5.0  3.4     1.5         0.2          0
25   5.0  3.0     1.6         0.2          0
26   5.0  3.4     1.6         0.4          0
35   5.0  3.2     1.2         0.2          0
40   5.0  3.5     1.3         0.3          0
43   5.0  3.5     1.6         0.6          0
49   5.0  3.3     1.4         0.2          0
60   5.0  2.0     3.5         1.0          1
62   6.0  2.2     4.0         1.0          1
78   6.0  2.9     4.5         1.5          1
83   6.0  2.7     5.1         1.6          1
85   6.0  3.4     4.5         1.6          1
93   5.0  2.3     3.3         1.0          1
119  6.0  2.2     5.0         1.5          2
138  6.0  3.0     4.8         1.8          2

In [45]:
df[
df["150"] > 100
]

Empty DataFrame
Columns: [150, 4, setosa, versicolor, virginica]
Index: []

In [47]:
df[
df["150"]>50000
]

Empty DataFrame
Columns: [150, 4, setosa, versicolor, virginica]
Index: []

In [48]:
df.at[2,"150"]

np.float64(4.7)

In [49]:
df[::-1]

     150    4  setosa  versicolor  virginica
149  5.9  3.0     5.1         1.8          2
148  6.2  3.4     5.4         2.3          2
147  6.5  3.0     5.2         2.0          2
146  6.3  2.5     5.0         1.9          2
145  6.7  3.0     5.2         2.3          2
..   ...  ...     ...         ...        ...
4    5.0  3.6     1.4         0.2          0
3    4.6  3.1     1.5         0.2          0
2    4.7  3.2     1.3         0.2          0
1    4.9  3.0     1.4         0.2          0
0    5.1  3.5     1.4         0.2          0

[150 rows x 5 columns]

In [53]:
#Check Missing Values

df.isnull()
df.isnull().sum()

150           0
4             0
setosa        0
versicolor    0
virginica     0
dtype: int64

In [55]:
df.notnull().sum()

150           150
4             150
setosa        150
versicolor    150
virginica     150
dtype: int64

In [ ]:
#Total Missing Values
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#drop bhi kar sakte ho missing values ko


df.dropna() # puri ki puri row hi delete ho jayegi / df.dropna(axis=0)

df.dropna(axis = 1) # jo bhi nan value hogi uska column hi delete ho jayega

df.dropna(how = "all") # agar puri row ya column hi nan hai to hi delete hoga

df.dropna(how = "any") # agar kisi bhi row ya column me nan value hai to hi delete ho jayega

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

    Fill Missing Values

In [58]:
df.fillna(0) # -- filling missing values with 0

df.fillna(df.mean())

df.fillna(df.median())

df.fillna(df.min())

df.fillna(df.max())

df.fillna(df.quantile(0.5))

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

    #if you want to fill the mean value of a column

In [60]:
df['150'].fillna(df['150'].mean())

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: 150, Length: 150, dtype: float64

In [ ]:
df["150"].fillna(
    df["150"].median()
)

In [61]:
df.replace("150", "Let")

     150    4  setosa  versicolor  virginica
0    5.1  3.5     1.4         0.2          0
1    4.9  3.0     1.4         0.2          0
2    4.7  3.2     1.3         0.2          0
3    4.6  3.1     1.5         0.2          0
4    5.0  3.6     1.4         0.2          0
..   ...  ...     ...         ...        ...
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

[150 rows x 5 columns]

In [63]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [64]:
df.duplicated().sum()

np.int64(1)

In [65]:
df.drop_duplicates(inplace=True)

In [66]:
df.rename(
columns={
"150":"Income"
}
)

     Income    4  setosa  versicolor  virginica
0       5.1  3.5     1.4         0.2          0
1       4.9  3.0     1.4         0.2          0
2       4.7  3.2     1.3         0.2          0
3       4.6  3.1     1.5         0.2          0
4       5.0  3.6     1.4         0.2          0
..      ...  ...     ...         ...        ...
145     6.7  3.0     5.2         2.3          2
146     6.3  2.5     5.0         1.9          2
147     6.5  3.0     5.2         2.0          2
148     6.2  3.4     5.4         2.3          2
149     5.9  3.0     5.1         1.8          2

[149 rows x 5 columns]

In [ ]:
df["Name"] = df["Name"].str.strip()  #for future project

df["Department"].str.upper()

df["Department"].str.lower()

df["Department"].str.capitalize()

    Find Missing Percentage

In [67]:
(df.isnull().sum()/len(df))*100

150           0.0
4             0.0
setosa        0.0
versicolor    0.0
virginica     0.0
dtype: float64

In [68]:
df.nunique()

150           35
4             23
setosa        43
versicolor    22
virginica      3
dtype: int64

In [70]:
df["150"].unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [72]:
df["150"].value_counts()

150
5.0    10
5.1     9
6.3     9
6.7     8
5.7     8
5.5     7
6.4     7
4.9     6
5.8     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: count, dtype: int64